In [1]:
#Import the Numpy package under the name np
import numpy as np

In [2]:
#Create a null vector of size 10
vector=np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Create a null vector of size 10 but the fifth value which is 1
vector=np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#Create a vector with values ranging from 10 to 49
x=np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [27]:
#Reverse a vector (the first element becomes last)
V=np.arange(10,15)
print("the original vector",V)
V=V[::-1]
print("the reversed vector",V)

the original vector [10 11 12 13 14]
the reversed vector [14 13 12 11 10]


In [6]:
#Create a 3x3 matrix with values ranging from 0 to 8
A=np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
#Find indices of non­zero elements from [1,2,0,0,4,0]
a=np.array([[1,2,0,0,4,0]])
np.nonzero(a)

(array([0, 0, 0], dtype=int64), array([0, 1, 4], dtype=int64))

In [17]:
#Create a 3x3x3 array with random values
np.random.random((3,3,3))

array([[[0.23946584, 0.4505313 , 0.35540969],
        [0.95800552, 0.16694322, 0.57125519],
        [0.01904274, 0.87844549, 0.58949205]],

       [[0.29687883, 0.7255763 , 0.39319433],
        [0.45997433, 0.63076377, 0.63227021],
        [0.56364753, 0.31838732, 0.04286734]],

       [[0.50258279, 0.97961657, 0.53612818],
        [0.99158654, 0.85481628, 0.18770734],
        [0.74835324, 0.67886135, 0.84902771]]])

In [9]:
#Create a random vector of size 30 and find the mean value
A=np.random.random((30))
A.mean()
print("the mean is")
print(A)

the mean is
[0.87339997 0.83422642 0.39363717 0.08206143 0.37532653 0.13380816
 0.58398728 0.71210423 0.53247611 0.03345478 0.47740258 0.20948382
 0.91947868 0.76211633 0.67417725 0.70622721 0.95833197 0.00394992
 0.78688298 0.0840536  0.4726129  0.29925837 0.5709783  0.84510239
 0.45663821 0.35335926 0.02226186 0.25965598 0.29668697 0.36680653]


In [10]:
#Create a 2d array with 1 on the border and 0 inside
x=np.ones((5,5))
print("the original array",x)
x[1:-1,1:-1]=0
print("with 1 on border and 0 inside",x)

the original array [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
with 1 on border and 0 inside [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#What is the major difference between sets, lists, tuples and dictionaries?
##lists are defined in square brackets,and are used to store the values in rows or coulmns.it allows duplicate values
##tuple is defined in (),it also allows duplicate values,they are immutable unlike lists
###set is unordered colletion of elements and are defined using{}
###dictionary is used to store the pair elements i.e, key and its value and it holds only single element

In [12]:
#Print first 10 natural numbers using while loop
a = 1
while(a<=10):
    print(a)
    a += 1

1
2
3
4
5
6
7
8
9
10


In [13]:
#Print the numbers -10 to -1 using for loop.
for i in range(-10,0,1):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [14]:
#Print the message “Done” after successful execution of any for a loop. 
for i in range(2):
    print(i)
else:
    print("Done!")

0
1
Done!


In [15]:
#Create a random vector of size 10 and sort it
a=np.random.random((10))
print("the random vector",a)
a.sort()
print("the sorted vector",a)

the random vector [0.95829274 0.16384645 0.60389949 0.17308917 0.15992084 0.37511864
 0.98451878 0.64888824 0.82488397 0.23918948]
the sorted vector [0.15992084 0.16384645 0.17308917 0.23918948 0.37511864 0.60389949
 0.64888824 0.82488397 0.95829274 0.98451878]


In [42]:
#Execute any three math functions using NumPy.
import numpy as np  
arr = np.array([0, 30, 60, 90, 120, 150, 180])  
print("The sin value is")  
print(np.sin(arr))  
print("The cosine value is")  
print(np.cos(arr))  
print("The tangent value is")  
print(np.tan(arr))  

The sin value is
[ 0.         -0.98803162 -0.30481062  0.89399666  0.58061118 -0.71487643
 -0.80115264]
The cosine value is
[ 1.          0.15425145 -0.95241298 -0.44807362  0.81418097  0.69925081
 -0.59846007]
The tangent value is
[ 0.         -6.4053312   0.32004039 -1.99520041  0.71312301 -1.02234624
  1.33869021]
